#ifndef __CONTROLS_H__
#define __CONTROLS_H__

/** VIRTUAL PINS **/
enum {
    VIPIN_LOCK = 0,
    VIPIN_LIGHT,
    VIPIN_DIST_FACE,
    VIPIN_DIST_FACE_FOOT,
    VIPIN_DIST_FOOT,
    VIPIN_DIST_WINDSCREEN_DEMISTER,
    VIPIN_DIST_WINDSCREEN_FOOT,
    VIPIN_DIST_REAR_DEMISTER,
    VIPIN_DIST_AIRCON,
    VIPIN_DIST_RECIRCULATE
};

enum {
//    VOPIN_LOCK = 0,
//    VOPIN_LIGHT,
    VOPIN_DIST_FACE = 0,
    VOPIN_DIST_FACE_FOOT,
    VOPIN_DIST_FOOT,
    VOPIN_DIST_WINDSCREEN_DEMISTER,
    VOPIN_DIST_WINDSCREEN_FOOT,
    VOPIN_DIST_REAR_DEMISTER,
    VOPIN_DIST_AIRCON,
    VOPIN_DIST_RECIRCULATE
};

/** PHYSICAL PINS **/
// INPUT REGISTER
#define INPUT_LOAD          5
#define INPUT_ENABLE        8
#define INPUT_CLOCK         6
#define INPUT_CHAINOUT      7

// LEDs REGSTER
#define LED_LATCH           3
#define LED_DATA            4
#define LED_OUTPUT_ENABLE   9

// CANBUS CONTROLLER
#define CAN_INTERRUPT       2
#define CAN_SELECT          10

#define LED_CLOCK   A0
#define PIN_FAN     A4
#define PIN_TEMP    A5

#endif
