#ifndef __CONTROLS_H__
#define __CONTROLS_H__

/** VIRTUAL PINS **/
enum {
    VPIN_LOCK = 0,
    VPIN_LIGHT,
    VPIN_DIST_FACE,
    VPIN_DIST_FACE_FOOT,
    VPIN_DIST_FOOT,
    VPIN_DIST_WINDSCREEN_DEMISTER,
    VPIN_DIST_WINDSCREEN_FOOT,
    VPIN_DIST_REAR_DEMISTER,
    VPIN_DIST_AIRCON,
    VPIN_DIST_RECIRCULATE
};
/*
#define VPIN_LOCK  0
#define VPIN_LIGHT 1
#define VPIN_DIST_FACE 2
#define VPIN_DIST_FACE_FOOT 3
#define VPIN_DIST_FOOT 4
#define VPIN_DIST_WINDSCREEN_DEMISTER 5
#define VPIN_DIST_WINDSCREEN_FOOT 6
#define VPIN_DIST_REAR_DEMISTER 7
#define VPIN_DIST_AIRCON 8
#define VPIN_DIST_RECIRCULATE 9
*/

/** PHYSICAL PINS **/
#define PIN_TEMP A5
#define PIN_FAN  A4

#endif
